version: "3.5"
services: 
  github-actions-node:
    image: actions-node
    build:
      context: docker-images/nodejs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  github-actions-nginx:
    image: actions-nginx
    build:
      context: docker-images/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - github-actions-node