# name: Docker Container Creation

# on: [push]

# env:
#   jf_url: ${{ secrets.JF_URL }}
#   jf_user: ${{ secrets.JF_USER }}
#   jf_access_token: ${{ secrets.JF_ACCESS_TOKEN }}


# jobs:
#   creating-docker-cntainer:
#     runs-on: self-hosted
#     steps:
#       - name: git checkout
#         uses: actions/checkout@v2

#       - name: configuring node
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: creating docker containers
#         run: |
#           docker-compose build
#           docker-compose up -d

#       # - name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v1

#       # - name: Set up Docker Buildx
#       #   uses: docker/setup-buildx-action@v1

#       # - name: Login to JFrog
#       #   uses: docker/login-action@v1
#       #   with:
#       #     registry: mskrishna123.jfrog.io
#       #     username: ${{ secrets.JF_USER }}
#       #     password: ${{ secrets.JF_ACCESS_TOKEN }}

#       # - name: Creating images
#       #   run: |
#       #       NODE_IMAGE_ID=$(docker images --filter=reference='actions-node:latest' -q)
#       #       docker tag $NODE_IMAGE_ID mskrishna123.jfrog.io/default-docker:v1
#       #       # docker push mskrishna123.jfrog.io/default-docker:v1
#       #       # docker rmi -f $(docker images -f "dangling=true" -q)

#       # - name: Push images to Jfrog
#       #   id: docker_build
#       #   uses: docker/build-push-action@v2
#       #   with:
#       #     push: true
#       #     tags: mskrishna123.jfrog.io/default-docker:v1
#       - name: Pushing the image to jfrog
#         run: |
#           docker login mskrishna123.jfrog.io
#           NODE_IMAGE_ID=$(docker images --filter=reference='actions-node:latest' -q)
#           docker tag $NODE_IMAGE_ID mskrishna123.jfrog.io/default-docker:v1
#           docker push mskrishna123.jfrog.io/default-docker:v1
#           # docker rmi -f $(docker images -f "dangling=true" -q)