name: Docker Container Creation

on: [push]

jobs:
  creating-docker-cntainer:
    runs-on: self-hosted
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: configuring node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: creating docker containers
        run: |
          docker-compose build
          docker-compose up -d
      - name: pushing image to jfrog
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}

          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          NODE_IMAGE_ID=docker images --filter=reference='actions-node:latest'
          docker tag $NODE_IMAGE_ID mskrishna123.jfrog.io/default-docker/docker-node:v1
          docker push mskrishna123.jfrog.io/default-docker/docker-node:v1
          docker rmi -f $(docker images -f "dangling=true" -q)