name: Docker Container Creation

on: [push]

jobs:
  creating-docker-cntainer:
    runs-on: self-hosted
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: configuring node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: creating docker containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          registry: mskrishna123.jfrog.io
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Pushing the image to jfrog
        run: |
          NODE_IMAGE_ID=$(docker images --filter=reference='actions-node:latest' -q)
          docker tag $NODE_IMAGE_ID mskrishna123.jfrog.io/default-docker:v1
          docker push mskrishna123.jfrog.io/default-docker:v1
          docker rmi -f $(docker images -f "dangling=true" -q)