name: nodejs Docker image Creation

on: 
  push:
    branches:
      - main

  # workflow_dispatch:

env:
  REGISTRY: mskrishna123.jfrog.io
  IMAGE_NAME: docker-node
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  creating-docker-image:
    runs-on: self-hosted
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Extracting docker metadata
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push images to Jfrog
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: docker-images/nodejs
          push: true
          tags: ${{ env.REGISTRY }}/docker-node/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
