name: nodejs Docker image Creation

on: 
  push:
    branches:
      - main
jobs:
  creating-docker-image:
    runs-on: self-hosted

    steps:
        - name: git checkout
          uses: actions/checkout@v3

        - name: pwd & ls
          run: |
            echo "Pwd"
            pwd
            echo "List contents"
            ls -la

        - name: docker build
          run: docker-compose build

        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v1        

        # - name: build and push
        #   uses: docker/build-push-action@v3
        #   with:
        #     context: .
        #     dockerfile: docker-images/nodejs/Dockerfile
        #     push: false

